### ISSUE TITLE
About Hidden dimension of Pred_Model in new_idea.ipynb.

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/CCDT#10]
Hello,

I wonder if there is a reason why you set the hidden_dim of Pred_Model to 64.

Also, I'm wondering if you've tried it in a deeper hidden dimension as well.

Thanks for reading.

**Comment by Kwon-sein** [comment]
First of all, thank you for your interest in my github.

The hidden dimension was experimented with 32, 64, and 128 respectively. 
Due to the small amount of our training data (number of samples : 1000), the dimensions of the model did not significantly affect performance. 
That's why I used 64 dims, which are universally used.

I hope my answer helped you.
Thanks.
