### ISSUE TITLE
About Kmeans label

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/CCDT#11]
You set 4 label that each color is 'navy', 'tomato', 'green', 'orange', but you practically use 3 label.

Why did you do that?

Thank you for reading.

**Comment by Kwon-sein** [comment]
First of all, thank you for your interest in my github.

When we proceed with kmeans, we experimented with two cases, one with three labels and the other with four. 
As a result of the execution, when there were 4 clusters, the classification prediction model gave poor results, which is thought to be because the classification was not effective because the data we had was too continuous.

Therefore, it showed better performance when K was 3, so 3 labels were used.

I hope my answer helped you.
Thanks.
