### ISSUE TITLE
About selection of clustering algorithm

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/CCDT#13]
When I looked at that code, the clustering technique used was K-MEANS. However, as far as I know, there are many other algorithms other than k-means that can be used as a clustering technique, especially for configuration data in the form of tabular data. So is there any reason why you used k-means instead of using other techniques?

**Comment by Kwon-sein** [comment]
First of all, thank you for your interest in my github.

Although not included in the code, I experimented with various clustering methods. (K-means, DBScan, Hierarchical clustering)
The silhouette coefficient was used to evaluate whether the cluster was well formed according to each cluster method, and as a result, it was confirmed that K-means clustered the data the best.
In particular, in the case of DBScan, it was confirmed that clustering did not work well because our data was too continuous.

If I get a chance, I'll add the results of this experiment as well.

Thank you.
