### ISSUE TITLE
About Scaler in new_idea.ipynb

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/CCDT#14]
Hello,

The current code uses StandardScaler and MinMaxScaler to scale the data, which adjusts the distribution of the data to help the learning algorithm perform better. 

However, depending on the characteristics of the data and the requirements of the model, different scaling methods may be more appropriate. 

For example, log transformation can be used to adjust the distribution of the data, or RobustScaler can be used to apply scaling that is less sensitive to outliers. 

I wonder if you've ever experimented with these different scaling methods. If so, I wonder what the results were.

Thanks for reading.

**Comment by Kwon-sein** [comment]
Hello.
First of all, thank you for your comments on my code.

1. Regarding the use of log transformation

I tried log transformation of the data, but the performance did not improve much.
I think the reason is that the distribution of the data did not change despite the log transformation because the range of the data was too wide.

2. About not using a scaler that can remove outliers

Regarding this, since the X(config) data used in the experiment is the data we created, we thought that improving performance by learning after removing the outliers would not be helpful when testing with other data in the future, so we set the outliers to I didn't use a scaler that can be removed.

I hope my answer was helpful and if you have any further questions please ask.
