### ISSUE TITLE
Top-K knob 

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/CCDT#16]
The code says that you get Top-K knob through the SHAP algorithm, but can I use LIME, PDP, Permutation Feature Importance instead of SHAP?

**Comment by Kwon-sein** [comment]
Hi,
Thanks for the question.

As you said, other algorithms such as LIME and PDP can be used in Top-K knob selection.

The reason I used the SHAP algorithm is because SHAP was the best performance used in the knob selection process of database parameter tuning papers.
The result of this proved with various experiments in the following papers.

_reference : **Zhang, Xinyi, et al. "Facilitating database tuning with hyper-parameter optimization: a comprehensive experimental evaluation." arXiv preprint arXiv:2110.12654 (2021).**_

Thank you for your kind comments.
