### ISSUE TITLE
About XGBRegressor in SMAC_with_our_data_twitter.ipynb

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/CCDT#17]
Hello,

In the current code, you are using fixed hyperparameter values in XGBRegressor. 
Hyperparameters are crucial factors that determine the performance of a model, and finding values optimized for a specific problem is crucial. 
Additionally, I'm wondering if you've applied hyperparameter tuning techniques such as Grid Search, Random Search, or Bayesian Optimization.

Thanks for reading.

**Comment by Kwon-sein** [comment]
Hi.

Thanks for the question.

Although not in the corresponding code, the parameters of XGBRegressor were tuned through Grid Search and Random Search, and the parameters that showed the best performance were fixedly used.

However, since the XGBRegressor model did not show very good performance even when the tuned parameters were used, it would be better to find out whether there are more suitable parameters through other tuning methods later.

Thank you for your kind comments.
