### ISSUE TITLE
pick Top-10 configuration

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/CCDT#20]
Ask about the content of the paper (A Study about Search Space of Job Range Reduction for Database Tuning).

Why pick Top-10 of configuration in Figure 1? Is it related to Knob range reduction?

**Comment by Kwon-sein** [comment]
Hi,

The reason for selecting the Top-10 configuration is the process corresponding to range reduction.

Since I assumed that there would be knobs that overlap with configurations with good performance, I performed range reduction by extracting not only the knob selection but also the top-10 configurations to solve the 'high-dimensional optimization' problem, which is a limitation of existing database parameter tuning.

Thank you for your question.
