### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/CCDT#7]
Hello, Thanks for your work,

In Jupyter_model.ipynb, why did't you remove outlier? 

<img width="609" alt="스크린샷 2023-03-10 오후 3 46 57" src="https://user-images.githubusercontent.com/53137088/224243811-03191db4-e000-4c3f-9c81-8f5708181de9.png">

I think this checked dot is outlier

**Comment by Kwon-sein** [comment]
Hi, Thanks for interesting about my code.
First of all, as written in the README.md, this jupyter file is the result about the data is not changed.

Also, since the data that we use in training is created by us, not formal data.
So I did not remove outliers because I thought that improving performance by removing outliers (with data created by us) was not correct model traing. 

I hope this answer has helped you with your questions.
Thanks.
